local positions = {
	vmath.vector3(225, 540, 0), -- 1
	vmath.vector3(640, 540, 0), -- 2
	vmath.vector3(1075, 540, 0), -- 3
	vmath.vector3(225, 175, 0), -- 4
	vmath.vector3(640, 175, 0), -- 5
	vmath.vector3(1075, 175, 0) -- 6
}

function init(self)
	
end

function on_message(self, message_id, message, sender)
	if message_id == hash("face_picker_positions") then
		for _, p in pairs(positions) do
			go.set_position(positions[message.position])
		end
	end
end
